### PR TITLE
Gifsupport

### PR DESCRIPTION
**Pull request by JohannesDeml**
- Add support for gifs and jpgs
- Documentation of the supported file types
- Sticker naming at export from set through Sticker.Name

### CODE REVIEW

**Comment by JohannesDeml** [comment]
As discussed, the PR got some additions:

- Automatic chagne to sequence if the file type is a gif
- Example files for gif, apng and png sequence
- Bug fixes

**Comment by JohannesDeml** [comment]
Did you find the time to check the PR? It has been a while ;)

**Comment by skjalgsm** [comment]
Yeah I know, sorry. We have some deadlines at work so I haven't had the
time unfortunately. I really appreciate the contribution though, its just
hard to find time right now :)

**Comment by JohannesDeml** [comment]
Ah I see, then take your time and great success with finishing the deadlines on schedule! 😃

**Comment by rfadeev** [comment]
@JohannesDeml Hi, I've been playing around with ordering of stickers in `StickerPack.asset` while testing #44 and found out that gif sticker should have `.sticker` extension rather than `.stickersequence`  in `Content.json` (while apng or png sequence with several files should have `.stickersequence`).

To fix that probably `StickerEditorUtility.IsAnimatedTexture` should be removed for `Sequence` to be false for gif stickers (as value of that field drives extension in #44). Would like to clarify what was the orginal idea behind that method? Asking as I cannot find any logic using value of `Sticker.Sequence` in master branch.

**Comment by JohannesDeml** [comment]
Hi @rfadeev 
Oh boy, I needed to dig into it a bit again, this was quite some time ago. The idea behind it, was to automatically set the type to sequence, since gifs will most likely be sequences. I remember, that I wanted to check if pngs have animations in them as well, but that task was just too much work for a little QoL feature.

So in general I would say: Kinda old code, that makes the usage less intuitive, because it only happens for gifs, so get rid of it.
But I'm wondering: gifs should never have the .stickersequence, even when they are a sequence? That would result in the need of making the Fps and Repetitions fields also editable when the sequence flag is not set.

**Comment by rfadeev** [comment]
@JohannesDeml Thanks for the response! I know, it's been a long time since this pull request was merged. I hoped to get any clues to understand the code better hence my message.

I understand now, `Sticker.Sequence` is used for editor purpose only to allow or disallow editing of fps and repetitions fields. Funny that those fields are still editable via nested asset inspector.

> But I'm wondering: gifs should never have the .stickersequence, even when they are a sequence? That would result in the need of making the Fps and Repetitions fields also editable when the sequence flag is not set.

Not sure I get what you mean correctly by "when they are a sequence". But I agree, need to allow editing of fps and repetitions as before. From that perspective maybe should not use `Sequence` proeprty to determine extension like it is now:
```csharp
var extension = sticker.Sequence ? ".stickersequence" : ".sticker";
```
but should add new property like `Extension` (enum of string) instead which would be serialized in asset. So then gif would have `Sequence` property true as before but `.sticker` extension based on `Extension` value.

Based on my experiments, when gif sticker uses `.stickersequence`, ordering of such sticker in Messages app gets incorrect. When it uses `.sticker`, ordering gets correct. For apng and png sequence it's vica versa: `.sticker` makes order broken and `.stickersequence` makes it correct. I tried to find Apple documentation on what extension gif should have, but in vain.

**Comment by JohannesDeml** [comment]
So what I was wondering is: If you export the gif as a .sticker, will it still be animated? If so, my suggestion would be:

Get rid of the readonly inspector logic and use the sequence as you intended to use it. An enum feels a bit over the top for now, since there are only two types. A bool is also quicker to edit in the editor :)

**Comment by rfadeev** [comment]
@JohannesDeml Got it, I remember it was animated in Messages app preview when you select sticker to send, but I did not send it as message, so need to check whether it's animated in sent mesage. Will do that on Monday once I get macOS machine to build and run.

Do you mean to get rid of readonly inspector logic completely or only for gifs?

Agree, Extension field feels like extra complexity but it allows to preserve current behaviour.

**Comment by JohannesDeml** [comment]
> Do you mean to get rid of readonly inspector logic completely or only for gifs?

I would suggest to completely get rid of the code, to have a consistent behavior. But in the end it's not my call, but @Skjalgsm one's.

> Agree, Extension field feels like extra complexity but it allows to preserve current behaviour.

True, but it also adds another field to the editor and makes the code more complex.

**Comment by rfadeev** [comment]
@JohannesDeml Can confirm gif sticker is animated when it uses `.sticker` extension in `Unity-iPhone-Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Content.json`. Checked Messages app preview and sent message using Xcode 11.3, iPhone 8 (11.4) simulator.

**Comment by JohannesDeml** [comment]
@rfadeev Cool, I think changing the logic as discussed would be the right step to proceed then!

**Pull request merged**
